version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: home_dashboard
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www

    queue:
        image: php:8.2-fpm
        container_name: home_dashboard_queue
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
